--USE opphomeworkunit2;
--
--INSERT INTO sales_rep (name) VALUES
--("Marco"), ("Alessio"), ("Jennifer"), ("Jonny"), ("Jackson");
--
--INSERT INTO lead_ (company_name, email, name, phone_number, sales_rep_lead_id) VALUE
--("Sony", "testla@tesla.com", "Marco", "432 32 5433", 1),
--("Tesla", "sony@sony.com", "Jonny", "543 362 76", 4);
--
--INSERT INTO account (city, country, employee_count, industry) VALUES
--("Paris", "France", "12", 1),
--("london", "england", "43", 2),
--("berlin", "Germany", "45", 3);
--
--
--INSERT INTO contact (name, company_name, email, phone_number, account_contact_id) VALUES
--("Jonny", "Tesla", "testla@tesla.com", "432 32 5433", 1),
--("Jackson", "Miao", "miao@miao.com", "43890 59430 3", 2),
--("Marco", "Sony", "sony@sony.com", "543 362 76", 3);
--
--
--INSERT INTO opportunity (product, quantity, status, account_opportunity_id, decision_maker_id, sales_rep_opportunity_id) VALUES
--(2, 14, 1, 1, 1, 4),
--(3, 9, 3, 1, 1, 4),
--(1, 10, 1, 1, 2, 4),
--(2, 15, 2, 2, 3, 1);